---
title: "MISTy_analysis"
author: "Tim Daniel Rose"
date: "2023-06-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(mistyR)
library(future)

# data manipulation
library(dplyr)
library(purrr)
library(distances)

# plotting
library(ggplot2)

#plan(multisession, workers=2)
plan(sequential)

library(rjson)

```


# Load data
```{r}
base_path = '/scratch/trose/misty/results'
files = list.files(base_path)
misty_results <- lapply(X=files, 
                        FUN=function(file, path){return(collect_results(file.path(path, file)))}, 
                        path=base_path)

JsonData <- fromJSON(file="analysis_config.json")
```

```{r}
cluster_tab <- function(cluster){
  return(tibble(formula=cluster$names, membership=cluster$membership))
}
```


```{r}
plot_view_contributions2 <- function(misty.results, trim = -Inf,
                                    trim.measure = c(
                                      "gain.R2", "multi.R2", "intra.R2",
                                      "gain.RMSE", "multi.RMSE", "intra.RMSE"
                                    )) {
  trim.measure.type <- match.arg(trim.measure)

  assertthat::assert_that(("contributions.stats" %in% names(misty.results)),
    msg = "The provided result list is malformed. Consider using collect_results()."
  )

  assertthat::assert_that(("improvements.stats" %in% names(misty.results)),
    msg = "The provided result list is malformed. Consider using collect_results()."
  )

  inv <- sign((stringr::str_detect(trim.measure.type, "gain") |
    stringr::str_detect(trim.measure.type, "RMSE", negate = TRUE)) - 0.5)

 targets <- misty.results$improvements.stats %>%
    dplyr::filter(
      measure == trim.measure.type,
      inv * mean >= inv * trim
    ) %>%
    dplyr::pull(target)
 
 plot.data <- misty.results$contributions.stats %>%
    dplyr::filter(target %in% targets)
 
 return(plot.data)
}

lapply(X=misty_results, FUN=plot_view_contributions2) %>% 
  bind_rows() %>%
  select(target, view, fraction) %>%
  filter(view=='intra') %>%
  group_by(target) %>%
  summarize(mean=mean(fraction), sd=sd(fraction), cnt = n()) %>%
  filter(!is.na(sd) & cnt > 2) %>%
  mutate(lower=mean-sd, upper=mean+sd) %>%
  arrange(mean) %>%
  mutate(target=factor(target, levels=target)) %>%
  filter(target !='C28H33O14') %>%
  ggplot(aes(x=target, y=mean)) +
  geom_col()+
  geom_errorbar(aes(ymin = lower, ymax = upper))+
  ggtitle('Intra view')+
  xlab('Mean Importance')+
  theme_light() +
  theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

lapply(X=misty_results, FUN=plot_view_contributions2) %>% 
  bind_rows() %>%
  select(target, view, fraction) %>%
  filter(view=='para.250') %>%
  group_by(target) %>%
  summarize(mean=mean(fraction), sd=sd(fraction), cnt = n()) %>%
  filter(!is.na(sd) & cnt > 2) %>%
  mutate(lower=mean-sd, upper=mean+sd) %>%
  arrange(mean) %>%
  mutate(target=factor(target, levels=target)) %>%
  filter(target !='C28H33O14') %>%
  ggplot(aes(x=target, y=mean)) +
  geom_col()+
  geom_errorbar(aes(ymin = lower, ymax = upper))+
  ggtitle('Para view')+
  xlab('Mean Importance')+
  theme_light() +
  theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
```


```{r}
plot_interaction_communities2 <- function(misty.results, view, cutoff = 1) {
  assertthat::assert_that(("importances.aggregated" %in% names(misty.results)),
    msg = "The provided result list is malformed. Consider using collect_results()."
  )

  assertthat::assert_that((view %in%
    (misty.results$importances.aggregated %>% dplyr::pull(view))),
  msg = "The selected view cannot be found in the results table."
  )

  view.wide <- misty.results$importances.aggregated %>%
    dplyr::filter(view == !!view) %>%
    tidyr::pivot_wider(
      names_from = "Target", values_from = "Importance",
      -c(view, nsamples)
    )


  assertthat::assert_that(
    all((view.wide %>%
      dplyr::select(-Predictor) %>% colnames() %>% sort()) ==
      (view.wide %>%
        dplyr::pull(Predictor)) %>% sort()),
    msg = "The predictor and target markers in the view must match."
  )

  assertthat::assert_that(requireNamespace("igraph",
    versionCheck = list(op = ">=", version = "1.2.7"),
    quietly = TRUE
  ),
  msg = "The package igraph (>= 1.2.7) is required to calculate the interaction communities."
  )

  A <- view.wide %>%
    dplyr::select(-Predictor) %>%
    as.matrix()
  A[A < cutoff | is.na(A)] <- 0

  # Workaround: fix binding check for variable . in this function context.
  # The reference to . below works just fine in its own scope
  . <- NULL

  G <- igraph::graph.adjacency(A, mode = "plus", weighted = TRUE) %>%
    igraph::set.vertex.attribute("name", value = names(igraph::V(.))) %>%
    igraph::delete.vertices(which(igraph::degree(.) == 0))
 
  return(G) 
}

#attrs <- rbind(as_data_frame(g, "vertices"), as_data_frame(g1, "vertices")) %>% unique()
#el <- rbind(as_data_frame(g), as_data_frame(g1))
```
```{r}
view='intra'
g = lapply(X=misty_results, FUN=plot_interaction_communities2, view=view, cutoff=0)

new_g <- bind_rows(lapply(X=g, FUN=igraph::as_data_frame)) %>%
  group_by(from, to) %>%
  summarize(weight=mean(weight), cnt=n()) %>%
  ungroup() %>%
  filter(cnt>2) %>%
  filter(weight>2) %>%
  filter(from !='C28H33O14') %>%
  filter(to !='C28H33O14') %>%
  igraph::graph_from_data_frame(directed = FALSE) %>%
  igraph::delete.vertices(which(igraph::degree(.) == 0))


C <- igraph::cluster_leiden(new_g)
cluster_tab(C) %>% write_csv(file=file.path(JsonData$store_dir, 'misty_intra_clusters.csv'))

layout <- igraph::layout_with_kk(new_g)

igraph::plot.igraph(new_g,
  layout = layout, mark.groups = C, main = view, vertex.size = 4,
  vertex.color = "black", vertex.label.dist = 1,
  vertex.label.color = "black", vertex.label.font = 2, vertex.label.cex = 0.66
  )
```



```{r}
view='para.250'
g = lapply(X=misty_results, FUN=plot_interaction_communities2, view=view, cutoff=0)

new_g <- bind_rows(lapply(X=g, FUN=igraph::as_data_frame)) %>%
  group_by(from, to) %>%
  summarize(weight=mean(weight), cnt=n()) %>%
  ungroup() %>%
  filter(cnt>2) %>%
  filter(weight>2) %>%
  filter(from !='C28H33O14') %>%
  filter(to !='C28H33O14') %>%
  igraph::graph_from_data_frame(directed = FALSE) %>%
  igraph::delete.vertices(which(igraph::degree(.) == 0))


C <- igraph::cluster_leiden(new_g)
cluster_tab(C) %>% write_csv(file=file.path(JsonData$store_dir, 'misty_para_clusters.csv'))

layout <- igraph::layout_with_fr(new_g)

igraph::plot.igraph(new_g,
  layout = layout, mark.groups = C, main = view, vertex.size = 4,
  vertex.color = "black", vertex.label.dist = 1,
  vertex.label.color = "black", vertex.label.font = 2, vertex.label.cex = 0.66
  )
```
```{r}
# C41H83N2O6P
# C39H79N2O6P
bind_rows(lapply(X=misty_results, FUN=function(x){return(x$importances.aggregated)})) %>%
  dplyr::filter(view == 'para.250') %>%
  filter(Target=='C39H79N2O6P') %>%
  filter(!is.na(Importance)) %>%
  group_by(Predictor, Target) %>%
  summarize(im=mean(Importance), isd=sd(Importance), cnt=n())%>%
  filter(cnt>2)%>%
  mutate(Importance=im) %>%
  mutate(lower=Importance-isd, upper=Importance+isd) %>%
  filter(Predictor !='C28H33O14') %>%
  arrange(desc(Importance)) %>%
  ungroup() %>%
  mutate(Predictor=factor(Predictor, levels=Predictor)) %>%
  ggplot(aes(x=Predictor, y=Importance)) +
  geom_col()+
  geom_errorbar(aes(ymin = lower, ymax = upper))+
  theme_light() +
  theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
```


```{r}
bind_rows(lapply(X=misty_results, FUN=function(x){return(x$importances.aggregated)})) %>%
  dplyr::filter(view == 'para.250') %>%
  filter(Target=='C39H79N2O6P') %>%
  filter(!is.na(Importance)) %>%
  group_by(Predictor, Target) %>%
  summarize(im=mean(Importance), isd=sd(Importance), cnt=n())%>%
  filter(cnt>2)%>%
  mutate(Importance=im) %>%
  mutate(lower=Importance-isd, upper=Importance+isd) %>%
  filter(Predictor !='C28H33O14') %>%
  arrange(desc(Importance)) %>%
  ungroup() %>%
  mutate(Predictor=factor(Predictor, levels=Predictor))
```


```{r}
bind_rows(lapply(X=misty_results, FUN=function(x){return(x$importances.aggregated)})) %>%
  dplyr::filter(view == 'intra') %>%
  filter(Target=='C39H79N2O6P') %>%
  filter(!is.na(Importance)) %>%
  group_by(Predictor, Target) %>%
  summarize(im=mean(Importance), isd=sd(Importance), cnt=n())%>%
  filter(cnt>2)%>%
  mutate(Importance=im) %>%
  mutate(lower=Importance-isd, upper=Importance+isd) %>%
  filter(Predictor !='C28H33O14') %>%
  arrange(desc(Importance)) %>%
  ungroup() %>%
  mutate(Predictor=factor(Predictor, levels=Predictor)) %>%
  ggplot(aes(x=Predictor, y=Importance)) +
  geom_col()+
  geom_errorbar(aes(ymin = lower, ymax = upper))+
  theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
```

```{r}
misty_results[[5]] %>% plot_contrast_heatmap("intra", "para.250", cutoff = 0.5)
```



























